"""The speeder rides with the horse's camera. GOAT676767 on Nexus, 7 October:
the camera sits too far back while riding, and should be closer, like a
normal third person driving view.

Every action record in the Wyvern's riding charts names one camera preset
from actionchart/xml/description/playercamerapreset.xml by the hashlittle of
its lower-case name. The lower chart's are Dragon_FollowCamera and
Dragon_StrideCamera, the RideOn chart's Dragon_Default, Dragon_FollowCamera,
Player_Ride_Wyvern and Dragon_Aim; the dragon presets sit 20 to 35 m back,
the Wyvern's 12 to 20. Each becomes a horse preset (7.5 m, 10.5 m zoomed
out); Dragon_Aim stays. The plugin serves its own copies of these charts, so
the Wyvern, Broomy and Kliff's charts keep their cameras.

    py -3 speeder/research/camera_patches.py CHARTS

CHARTS holds the shipped m0004_ride_dragon_lower.paac and
m0004_ride_dragon_upper.paac. Needs Broomy's private/research on the path
for hashlittle. Writes mod/src/game/camerapatches.h.
"""
import os
import struct
import sys

sys.path.insert(0, os.environ.get("BROOMY_RESEARCH", os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "Broomy", "private", "research")))
import hashlittle as hl   # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "mod", "src", "game", "camerapatches.h")
SIZE = 0x114
CHARTS = [(1, "m0004_ride_dragon_lower.paac"), (2, "m0004_ride_dragon_upper.paac")]
SWAPS = {
    "dragon_followcamera": "player_ride_horse_run",
    "dragon_stridecamera": "player_ride_horse_fast_run",
    "dragon_default": "player_ride_horse",
    "player_ride_wyvern": "player_ride_horse_run",
}
KEEP = ["dragon_aim"]


def h(name):
    return hl.hashlittle(name.encode())


def main():
    folder = sys.argv[1]
    rows = []
    for chart, name in CHARTS:
        d = open(os.path.join(folder, name), "rb").read()
        sites = {}
        for old in list(SWAPS) + KEEP:
            v = struct.pack("<I", h(old))
            at = d.find(v)
            while at >= 0:
                sites[at] = old
                at = d.find(v, at + 1)
        if not sites:
            sys.exit("%s names none of the cameras" % name)
        first = min(sites)
        for at in sorted(sites):
            # One camera per action record: every site is a whole number of
            # records from the first, and the four bytes after it are zero.
            if (at - first) % SIZE or d[at + 4:at + 8] != b"\0\0\0\0":
                sys.exit("%s: a camera hash at +0x%X is not in an action record's camera field" % (name, at))
            old = sites[at]
            if old in KEEP:
                continue
            rows.append((chart, at, h(old), h(SWAPS[old]), name[:-5], old, SWAPS[old]))
        print("%s: %d cameras, %d swapped" % (name, len(sites), sum(1 for r in rows if r[0] == chart)))
    with open(OUT, "w", newline="\n") as f:
        f.write("#pragma once\n#include <cstdint>\n\n#include \"game/hoverpatches.h\"\n\n")
        f.write("// Generated by speeder/research/camera_patches.py from the Wyvern's\n")
        f.write("// charts (build 1.0.0.2976). Each riding action's camera preset is the\n")
        f.write("// horse's instead of the dragon's or the Wyvern's; Dragon_Aim stays.\n")
        f.write("namespace bm::broomchart\n{\n    inline constexpr HoverPatch kCameraPatches[] = {\n")
        for chart, at, old, new, cname, oname, nname in rows:
            f.write("        { %d, 0x%05X, 0x%08X, 0x%08X },   // %s %s -> %s\n" % (chart, at, old, new, cname, oname, nname))
        f.write("    };\n}\n")
    print("wrote", os.path.normpath(OUT), len(rows))


if __name__ == "__main__":
    main()
