#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/boost_patches.py from the Wyvern's
// riding lower chart (build 1.0.0.2976). In Camera flight control the run
// key goes to the acceleration state, as it does in Manual.
namespace bm::broomchart
{
    inline constexpr HoverPatch kBoostPatches[] = {
        { 1, 0x0F84E, 0x410EEFBF, 0x0E23DEE4 },   // m0004_ride_dragon_lower b51 target: dive -> acceleration
        { 1, 0x0F862, 0x01010000, 0x01000000 },   // m0004_ride_dragon_lower b51 cond_count 1 -> 0
        { 1, 0x01BBC, 0x00000000, 0x447A0000 },   // m0004_ride_dragon_lower 0E23DEE4 vertical window time_start 0.00 -> 1000
        { 1, 0x01BC0, 0x40422222, 0x447A0000 },   // m0004_ride_dragon_lower 0E23DEE4 vertical window time_end 3.03 -> 1000
        { 1, 0x01E16, 0x00000000, 0x447A0000 },   // m0004_ride_dragon_lower 0E23DEE4 vertical window time_start 0.00 -> 1000
        { 1, 0x01E1A, 0x40422222, 0x447A0000 },   // m0004_ride_dragon_lower 0E23DEE4 vertical window time_end 3.03 -> 1000
        { 1, 0x01730, 0x00000000, 0x447A0000 },   // m0004_ride_dragon_lower 570E1E87 vertical window time_start 0.00 -> 1000
        { 1, 0x01734, 0x40422222, 0x447A0000 },   // m0004_ride_dragon_lower 570E1E87 vertical window time_end 3.03 -> 1000
        { 1, 0x0198A, 0x00000000, 0x447A0000 },   // m0004_ride_dragon_lower 570E1E87 vertical window time_start 0.00 -> 1000
        { 1, 0x0198E, 0x40422222, 0x447A0000 },   // m0004_ride_dragon_lower 570E1E87 vertical window time_end 3.03 -> 1000
        { 1, 0x01ADC, 0xFFFF0000, 0xFFFF0A00 },   // m0004_ride_dragon_lower 0E23DEE4 moves like cruise (header +0x41 0x00 -> 0x0A)
        { 1, 0x01D36, 0xFFFF0000, 0xFFFF0A00 },   // m0004_ride_dragon_lower 0E23DEE4 moves like cruise (header +0x41 0x00 -> 0x0A)
        { 1, 0x01650, 0xFFFF0000, 0xFFFF0A00 },   // m0004_ride_dragon_lower 570E1E87 moves like cruise (header +0x41 0x00 -> 0x0A)
        { 1, 0x018AA, 0xFFFF0000, 0xFFFF0A00 },   // m0004_ride_dragon_lower 570E1E87 moves like cruise (header +0x41 0x00 -> 0x0A)
        { 1, 0x0B784, 0x00000100, 0x00000000 },   // m0004_ride_dragon_lower 0E23DEE4 action +0x5D 1 -> 0, free to climb and dive
        { 1, 0x0C138, 0x00000100, 0x00000000 },   // m0004_ride_dragon_lower 570E1E87 action +0x5D 1 -> 0, free to climb and dive
    };
}
