#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/effect_patches.py from the Wyvern's
// charts (build 1.0.0.2976). Camera shakes, rumble, blur and effects point
// at a sound event quietpatches.h has zeroed, so they do nothing.
namespace bm::broomchart
{
    inline constexpr HoverPatch kEffectPatches[] = {
        { 0, 0x01B33, 0x00000181, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x01E23, 0x00000181, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x02113, 0x00000181, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x02403, 0x00000181, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06F59, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06F6D, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06F95, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06FA9, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06FBD, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06FD1, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x06FE5, 0x000003C0, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x070EB, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x070FF, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07127, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0713B, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0714F, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07163, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07177, 0x000003C0, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0727D, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07291, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x072B9, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x072CD, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x072E1, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x072F5, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07309, 0x000003C0, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0740F, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07423, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0744B, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0745F, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07473, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07487, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0749B, 0x000003C0, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x075A1, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x075B5, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x075DD, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x075F1, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07605, 0x00000310, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07619, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0762D, 0x000003C0, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07803, 0x00000498, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x078F5, 0x00000498, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x079E7, 0x00000498, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07AD9, 0x00000498, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x07BCB, 0x00000498, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0AD5F, 0x00000605, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x0B21D, 0x00000605, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x0B6DB, 0x00000605, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x0B861, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x0B875, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x0BBD1, 0x00000605, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x0C4AF, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0C4C3, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0C4D7, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0C4EB, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0C4FF, 0x00000788, 0x0000004E },   // m0004_dragon_upper blur
        { 0, 0x0C527, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0C53B, 0x00000780, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0C693, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0C6A7, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0C6BB, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0C6CF, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0C6E3, 0x00000788, 0x0000004E },   // m0004_dragon_upper blur
        { 0, 0x0C6F7, 0x000007D3, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0C70B, 0x0000082B, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0C733, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0C747, 0x00000780, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0CB95, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CBA9, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CBE5, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CBF9, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC0D, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC21, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC35, 0x000003C0, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC49, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC5D, 0x00000260, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC71, 0x000002B8, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CC85, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CE33, 0x00000883, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CE6F, 0x00000883, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CE83, 0x00000883, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0CE97, 0x00000883, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0D52D, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0D541, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0D555, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0D569, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0D57D, 0x00000788, 0x0000004E },   // m0004_dragon_upper blur
        { 0, 0x0D5A5, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0D5B9, 0x00000780, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0D799, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0D7AD, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0D7C1, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0D7D5, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0D7E9, 0x00000788, 0x0000004E },   // m0004_dragon_upper blur
        { 0, 0x0D7FD, 0x000007D3, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0D811, 0x0000082B, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0D839, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x0D84D, 0x00000780, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x0DAA1, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DAB5, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DAC9, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DBCB, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DBDF, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DBF3, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DCF5, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DD09, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0DD1D, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E0FD, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E125, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E139, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E23B, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E263, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E277, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E379, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E3A1, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E3B5, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E4A3, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E4B7, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E4CB, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E5CD, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E5E1, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E5F5, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E6F7, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E70B, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0E71F, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EB13, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EB3B, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EB4F, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EC79, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0ECA1, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0ECB5, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EDDF, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EE07, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EE1B, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EF09, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EF1D, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0EF31, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F033, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F047, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F05B, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F15D, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F171, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F185, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F579, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F5A1, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F5B5, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F6F3, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F72F, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F743, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F859, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F881, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0F895, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0FA3D, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0FA65, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x0FA79, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x101E7, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x101FB, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1020F, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10311, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10325, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10339, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1043B, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1044F, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10463, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10857, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1087F, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10893, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x10C03, 0x00000B31, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x10C17, 0x00000B8B, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x11545, 0x00000D2C, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x11559, 0x00000D84, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1156D, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x115A9, 0x00000DDC, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x115D1, 0x00000E34, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x116D9, 0x00000E90, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x11701, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1173D, 0x00000D84, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x11751, 0x00000368, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x11779, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1178D, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x117A1, 0x00000DDC, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x117B5, 0x00000E34, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x118BB, 0x00000E90, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x118CF, 0x00000E90, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x118F7, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1196F, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x11983, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x12629, 0x00000FFD, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x1263D, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x12651, 0x00000788, 0x0000004E },   // m0004_dragon_upper blur
        { 0, 0x12665, 0x0000100B, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x12679, 0x00001063, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1268D, 0x000010BB, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x126A1, 0x00001113, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x127CF, 0x00000883, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x13FE9, 0x00000E90, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x14039, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1404D, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x14061, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x14603, 0x00000605, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x14797, 0x00000E90, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x14923, 0x00001246, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x14937, 0x00001254, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1494B, 0x000012AC, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1495F, 0x00001304, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x14973, 0x0000135C, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1499B, 0x000013B4, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x149AF, 0x0000140C, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x149C3, 0x00001246, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x149EB, 0x00001464, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x149FF, 0x000014BC, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x14A13, 0x00001246, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x14F85, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x14F99, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x14FAD, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x14FC1, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x151A5, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x151B9, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x153B1, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x153C5, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x153D9, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x153ED, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x155D1, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x155E5, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x157DD, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x157F1, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15805, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15819, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x159FD, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15A11, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15C09, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15C1D, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15C31, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15C45, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15E29, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x15E3D, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16011, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16025, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16039, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1604D, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16231, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16245, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16419, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1642D, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16441, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16455, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16639, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1664D, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16821, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16835, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16849, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1685D, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16A41, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16A55, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16C29, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16C3D, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16C51, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16C65, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16E49, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x16E5D, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x17031, 0x00001588, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x17045, 0x000015E2, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x17059, 0x0000163C, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1706D, 0x00001696, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x17251, 0x0000065F, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x17265, 0x000006B9, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x17B41, 0x000016F0, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x17B55, 0x000016FE, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x184F9, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1850D, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x18521, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x187C1, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x187D5, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x187E9, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x18997, 0x00000942, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x189AB, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x189BF, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x18C5F, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x18C73, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x18C87, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19E41, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19E69, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19E91, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19EA5, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19EB9, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19ECD, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x19FDB, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A003, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A017, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A02B, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A03F, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A053, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A161, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A189, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A19D, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A1B1, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A1C5, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A1D9, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A2E7, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A2FB, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A323, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A337, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A34B, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A35F, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A481, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A495, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A4A9, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A4BD, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A4D1, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A4E5, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A607, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A61B, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A62F, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A643, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A657, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A66B, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A779, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A78D, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A7B5, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A7C9, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A7DD, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A7F1, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A913, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A927, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A93B, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A94F, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A963, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1A977, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AA99, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AAAD, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AAC1, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AAD5, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AAE9, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AAFD, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1ABFF, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AC13, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AC3B, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AC4F, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AC63, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AC77, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AD65, 0x000019C6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AD79, 0x00001A1E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1ADA1, 0x00001A76, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1ADB5, 0x00001B7E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1ADC9, 0x00001ACE, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1ADDD, 0x00001B26, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AEBB, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AECF, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1AEE3, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1B1BF, 0x00001BE1, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1B48D, 0x00001BE1, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1B629, 0x00001D15, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1B927, 0x00001BE1, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1BB2B, 0x00001D15, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1C745, 0x00001E06, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1C759, 0x00001EB6, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1C781, 0x00001E5E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1C8AB, 0x00001E06, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1C8BF, 0x00001EB6, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1C8E7, 0x00001E5E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1CA11, 0x00001E06, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1CA25, 0x00001EB6, 0x0000004E },   // m0004_dragon_upper effect switch
        { 0, 0x1CA4D, 0x00001E5E, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1E5DF, 0x00000E90, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1E607, 0x000009F6, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1E61B, 0x000008EA, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1E62F, 0x0000099A, 0x0000004E },   // m0004_dragon_upper effect
        { 0, 0x1EADF, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x1EAF3, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x1EB07, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x1EB1B, 0x00000778, 0x0000004E },   // m0004_dragon_upper rumble
        { 0, 0x1EB2F, 0x00000788, 0x0000004E },   // m0004_dragon_upper blur
        { 0, 0x1EB57, 0x0000076A, 0x0000004E },   // m0004_dragon_upper camera shake
        { 0, 0x1EB6B, 0x00000780, 0x0000004E },   // m0004_dragon_upper rumble
        { 1, 0x00803, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00817, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0083F, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00853, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00867, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0087B, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x008A3, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x008B7, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00C7B, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00C8F, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00CB7, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00CCB, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00CDF, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00CF3, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00D1B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x00D2F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x010F3, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01107, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0112F, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01143, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01157, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0116B, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01193, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x011A7, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01399, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x013AD, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x013D5, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x013E9, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0154F, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01563, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0158B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0159F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x015B3, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x015C7, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x015EF, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01603, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0180D, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01821, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01849, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0185D, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x019DB, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x019EF, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01A17, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01A2B, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01A3F, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01A53, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01A7B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01A8F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01C99, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01CAD, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01CD5, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01CE9, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01E67, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01E7B, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01EA3, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01EB7, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01ECB, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01EDF, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01F07, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x01F1B, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02125, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02139, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02161, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02175, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x022F3, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02307, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0232F, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02343, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02357, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0236B, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02393, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x023A7, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02577, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02733, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02747, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02951, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02965, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0298D, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x029A1, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02B1F, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02B33, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02B5B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02B6F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02B83, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02B97, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02BBF, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02BD3, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02DC5, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02DD9, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02E01, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02E15, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02F7B, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02F8F, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02FB7, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02FCB, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02FDF, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x02FF3, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0301B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0302F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03239, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0324D, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03275, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03289, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03407, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0341B, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03443, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03457, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0346B, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0347F, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x034A7, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x034BB, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x036AD, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x036C1, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x036E9, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x036FD, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03863, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03877, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0389F, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x038B3, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x038C7, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x038DB, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03903, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03917, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03B21, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03B35, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03B5D, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03B71, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03CEF, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03D03, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03D2B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03D3F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03D53, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03D67, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03D8F, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03DA3, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x03F81, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x03FA9, 0x000003C5, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x03FBD, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x03FD1, 0x000003C5, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x03FE5, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x03FF9, 0x000003C5, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0400D, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04021, 0x000003C5, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04035, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0405D, 0x000003C5, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04071, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04085, 0x000003C5, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04099, 0x0000041D, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0441D, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04431, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04459, 0x00000258, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0446D, 0x000002B2, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x045EB, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x045FF, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04627, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0463B, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0464F, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04663, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0468B, 0x0000015C, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0469F, 0x000001B6, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04857, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x049FB, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04A0F, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04BDF, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04D9B, 0x000000A8, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04DAF, 0x00000102, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x04F19, 0x000005C6, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04F2D, 0x00000676, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04F69, 0x00000489, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x04F7D, 0x00000491, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x04F91, 0x0000049F, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x04FA5, 0x0000061E, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04FB9, 0x000006CE, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x04FF5, 0x000005C6, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05009, 0x00000676, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05031, 0x000004B0, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05045, 0x00000508, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05059, 0x00000560, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x051FF, 0x000005C6, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05213, 0x00000676, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0524F, 0x00000489, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x05263, 0x00000491, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x05277, 0x0000049F, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x0528B, 0x0000061E, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0529F, 0x000006CE, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x052DB, 0x000005C6, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x052EF, 0x00000676, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05317, 0x000004B0, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0532B, 0x00000508, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0533F, 0x00000560, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05953, 0x00000806, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x059CB, 0x00000817, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x059DF, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x059F3, 0x00000817, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05A07, 0x0000086F, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x05CBB, 0x00000806, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x05D33, 0x00000817, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05D47, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x05D5B, 0x00000817, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x05D6F, 0x0000086F, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x06023, 0x00000806, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x0609B, 0x000008D7, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x060AF, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x060C3, 0x000008D7, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x060D7, 0x0000086F, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0638B, 0x00000806, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x06403, 0x000008D7, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x06417, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x0642B, 0x000008D7, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0643F, 0x0000086F, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x07045, 0x00000A60, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07059, 0x00000A6E, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0706D, 0x00000A76, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x071BD, 0x00000AC1, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x071D1, 0x00000A6E, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x071E5, 0x00000A76, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x0720D, 0x00000ACF, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x07221, 0x00000B27, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x07235, 0x00000B7F, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0725D, 0x00000BDD, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x07471, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x07499, 0x00000C6F, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x074C1, 0x00000A6E, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x074E9, 0x00000A76, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x076FB, 0x00000BDD, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0770F, 0x00000ACF, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x07723, 0x00000D35, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0774B, 0x00000C85, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x0775F, 0x00000CDD, 0x00000005 },   // m0004_ride_dragon_lower effect
        { 1, 0x078ED, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07901, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0793D, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07951, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0798D, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x079A1, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x079C9, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x079DD, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x07CA9, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07CBD, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x07CF9, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07D0D, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x07D49, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07D5D, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x07D85, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x07D99, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x08051, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08065, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x080B5, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x080C9, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x080F1, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08105, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x08141, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08155, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0840D, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08421, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x08435, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08449, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0845D, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08471, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x08485, 0x00000E10, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x08499, 0x00000C7D, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x089F7, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x08BAF, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x08D67, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x08F0B, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x09267, 0x00000EE8, 0x00000005 },   // m0004_ride_dragon_lower camera shake switch
        { 1, 0x0927B, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0928F, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x092B7, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x092CB, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x092DF, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x092F3, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x09307, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0931B, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0932F, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x09343, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x09357, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0936B, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x0937F, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x09393, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x093A7, 0x00000EFA, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x093BB, 0x00000F02, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x095DF, 0x00000F0D, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x095F3, 0x00000F1E, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x0962F, 0x0000036B, 0x00000005 },   // m0004_ride_dragon_lower effect switch
        { 1, 0x09AEF, 0x00000F7E, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x09B03, 0x00000F8C, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x09B17, 0x00000F1E, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 1, 0x09FC3, 0x00000F7E, 0x00000005 },   // m0004_ride_dragon_lower camera shake
        { 1, 0x09FD7, 0x00000F8C, 0x00000005 },   // m0004_ride_dragon_lower rumble
        { 1, 0x09FEB, 0x00000F1E, 0x00000005 },   // m0004_ride_dragon_lower blur
        { 2, 0x00433, 0x00000155, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x00447, 0x000001AF, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0046F, 0x00000209, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x00483, 0x00000263, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x00497, 0x00000155, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x004AB, 0x000001AF, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x004D3, 0x00000209, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x004E7, 0x00000263, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x00AAB, 0x0000037F, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x0157F, 0x00000466, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x01687, 0x00000503, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x019B7, 0x00000615, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01AE5, 0x000006E3, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01DE5, 0x00000780, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01DF9, 0x000007DA, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E0D, 0x00000834, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E21, 0x0000088E, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E35, 0x000008E8, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E49, 0x000008E8, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E5D, 0x00000942, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E71, 0x0000099C, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01E99, 0x000009F6, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01EAD, 0x000009F6, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01EC1, 0x00000A50, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x01ED5, 0x00000AAA, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0220F, 0x00000780, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02223, 0x000007DA, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02237, 0x00000834, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0224B, 0x0000088E, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0225F, 0x000008E8, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02273, 0x000008E8, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02287, 0x00000942, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0229B, 0x0000099C, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x022C3, 0x000009F6, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x022D7, 0x000009F6, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x022EB, 0x00000A50, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x022FF, 0x00000AAA, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02639, 0x00000780, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0264D, 0x000007DA, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02661, 0x00000834, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02675, 0x0000088E, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02689, 0x000008E8, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0269D, 0x000008E8, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x026B1, 0x00000942, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x026C5, 0x0000099C, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02715, 0x000009F6, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02729, 0x000009F6, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x0273D, 0x00000A50, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x02751, 0x00000AAA, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x031E3, 0x00000C40, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x032FF, 0x00000503, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03443, 0x00000C40, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x0355F, 0x00000503, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x036A3, 0x00000CE2, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x037D3, 0x00000D3A, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03903, 0x00000D92, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03A2B, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03A3F, 0x00000DFA, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03A53, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03A67, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03A7B, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03A8F, 0x00000DF2, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03AB7, 0x00000E0C, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03ADF, 0x00000CE2, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03C07, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03C1B, 0x00000DFA, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03C2F, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03C43, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03C57, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03C6B, 0x00000DF2, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03C93, 0x00000E0C, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03CBB, 0x00000CE2, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03DCF, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03DE3, 0x00000DFA, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03DF7, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03E0B, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03E1F, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03E33, 0x00000DF2, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03E5B, 0x00000E0C, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03E83, 0x00000D3A, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03F97, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03FAB, 0x00000DFA, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x03FBF, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03FD3, 0x00000DEA, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x03FE7, 0x00000E68, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x03FFB, 0x00000DF2, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04023, 0x00000E0C, 0x00000034 },   // m0004_ride_dragon_upper camera shake switch
        { 2, 0x0404B, 0x00000D92, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x041A7, 0x00000615, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x042E9, 0x000006E3, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x04559, 0x00000EC0, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x04A61, 0x00001014, 0x00000034 },   // m0004_ride_dragon_upper camera shake
        { 2, 0x04A75, 0x00001022, 0x00000034 },   // m0004_ride_dragon_upper blur
        { 2, 0x04A89, 0x00001033, 0x00000034 },   // m0004_ride_dragon_upper blur
        { 2, 0x04AB1, 0x00001052, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04AC5, 0x00001076, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x04BCD, 0x00001014, 0x00000034 },   // m0004_ride_dragon_upper camera shake
        { 2, 0x04BE1, 0x00001022, 0x00000034 },   // m0004_ride_dragon_upper blur
        { 2, 0x04BF5, 0x00001033, 0x00000034 },   // m0004_ride_dragon_upper blur
        { 2, 0x04C1D, 0x00001076, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x04C31, 0x000011B8, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04C81, 0x00001052, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04C95, 0x00001052, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04CA9, 0x00001052, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04CBD, 0x00001052, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04CD1, 0x00001052, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04DB3, 0x000012C4, 0x00000034 },   // m0004_ride_dragon_upper effect switch
        { 2, 0x04DEF, 0x00001215, 0x00000034 },   // m0004_ride_dragon_upper camera shake
        { 2, 0x04E03, 0x00001223, 0x00000034 },   // m0004_ride_dragon_upper blur
        { 2, 0x04E17, 0x00001234, 0x00000034 },   // m0004_ride_dragon_upper blur
        { 2, 0x04E2B, 0x00001245, 0x00000034 },   // m0004_ride_dragon_upper rumble
        { 2, 0x04EA3, 0x0000131E, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04EB7, 0x0000131E, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04ECB, 0x00001376, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04EDF, 0x000013CE, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04EF3, 0x00001426, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04F07, 0x0000147E, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04F1B, 0x000014D6, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04F2F, 0x0000152E, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04F57, 0x00001586, 0x00000034 },   // m0004_ride_dragon_upper effect
        { 2, 0x04F6B, 0x000015DE, 0x00000034 },   // m0004_ride_dragon_upper effect
    };
}
