#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/flourish_patches.py from the
// Wyvern's charts (build 1.0.0.2976). Every branch into a roll or a glide
// gets frame tag 0x27, which no clip window carries, so it never fires.
namespace bm::broomchart
{
    inline constexpr HoverPatch kFlourishPatches[] = {
        { 0, 0x31488, 0x8CCB6025, 0xE851DFDF },   // m0004_dragon_upper b93 target 8CCB6025 -> E851DFDF, the end of that glide
        { 0, 0x314BC, 0x08415CA5, 0xDD65089B },   // m0004_dragon_upper b94 target 08415CA5 -> DD65089B, the end of that glide
        { 1, 0x0EE3E, 0x04282800, 0x04282700 },   // m0004_ride_dragon_lower b1 -> 8D6C25B2
        { 1, 0x0EF0E, 0x04282800, 0x04282700 },   // m0004_ride_dragon_lower b5 -> 8D6C25B2
        { 1, 0x0EF42, 0x04282800, 0x04282700 },   // m0004_ride_dragon_lower b6 -> 8AE6B609
        { 1, 0x0F14A, 0x1E281000, 0x1E282700 },   // m0004_ride_dragon_lower b16 -> 8D6C25B2
        { 1, 0x0F17E, 0x1E281000, 0x1E282700 },   // m0004_ride_dragon_lower b17 -> 8AE6B609
        { 1, 0x0F89A, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b52 -> D8208390
        { 1, 0x0F9D2, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b58 -> 75E9710E
        { 1, 0x0FAD6, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b63 -> A86AAA5D
        { 1, 0x10E56, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b159 -> 6DCA12C9
        { 2, 0x0D3F8, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b95 -> 3BCA48F0
        { 2, 0x0D42C, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b96 -> BE97C31F
        { 2, 0x0D494, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b98 -> 093553DC
    };
}
