#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by speeder/research/ground_patches.py from the Wyvern's charts
// (build 1.0.0.2976). Every branch into a state in the air, the takeoff
// among them, gets frame tag 0x27, which no clip window carries, so it
// never fires: the speeder stays on the ground.
namespace bm::broomchart
{
    inline constexpr HoverPatch kGroundPatches[] = {
        { 1, 0x0EE3E, 0x04282800, 0x04282700 },   // m0004_ride_dragon_lower b1 -> 8D6C25B2
        { 1, 0x0EF42, 0x04282800, 0x04282700 },   // m0004_ride_dragon_lower b6 -> 8AE6B609
        { 1, 0x0EFAA, 0x1E280F00, 0x1E282700 },   // m0004_ride_dragon_lower b8 -> 608F3105
        { 1, 0x0EFDE, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b9 -> 968E1E3C
        { 1, 0x0F046, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b11 -> 7235DF7D
        { 1, 0x0F07A, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b12 -> 7235DF7D
        { 1, 0x0F0AE, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b13 -> 2B1E3C7C
        { 1, 0x0F0E2, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b14 -> E066175D
        { 1, 0x0F116, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b15 -> E066175D
        { 1, 0x0F14A, 0x1E281000, 0x1E282700 },   // m0004_ride_dragon_lower b16 -> 8D6C25B2
        { 1, 0x0F17E, 0x1E281000, 0x1E282700 },   // m0004_ride_dragon_lower b17 -> 8AE6B609
        { 1, 0x0F1B2, 0x04282800, 0x04282700 },   // m0004_ride_dragon_lower b18 -> 117F8F51
        { 1, 0x0F1E6, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b19 -> 117F8F51
        { 1, 0x0F21A, 0x1E280F00, 0x1E282700 },   // m0004_ride_dragon_lower b20 -> 117F8F51
        { 1, 0x0F24E, 0x1E280F00, 0x1E282700 },   // m0004_ride_dragon_lower b21 -> 117F8F51
        { 1, 0x0F72E, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b45 -> 570E1E87
        { 1, 0x0F762, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_lower b46 -> 38BD703A
        { 2, 0x0C350, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b13 -> E066175D
        { 2, 0x0C3B8, 0x1E280F00, 0x1E282700 },   // m0004_ride_dragon_upper b15 -> E066175D
        { 2, 0x0C3EC, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b16 -> E066175D
        { 2, 0x0C5C0, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b25 -> E066175D
        { 2, 0x0C5F4, 0x04280F00, 0x04282700 },   // m0004_ride_dragon_upper b26 -> 117F8F51
        { 2, 0x0D120, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b81 -> 5FF14EB6
        { 2, 0x0D188, 0x1E282800, 0x1E282700 },   // m0004_ride_dragon_upper b83 -> 5FF14EB6
        { 2, 0x0D1F0, 0x1E280F00, 0x1E282700 },   // m0004_ride_dragon_upper b85 -> 117F8F51
    };
}
