#pragma once
#include <cstdint>

// Generated by private/research/newmount/hover_patches.py from the Wyvern's
// riding charts (build 1.0.0.2976). Every branch into a ground state goes to
// the flight state E066175D, so Broomy never lands or walks.
namespace bm::broomchart
{
    struct HoverPatch { int chart; uint32_t at; uint32_t wyvern; uint32_t broomy; };
    inline constexpr HoverPatch kHoverPatches[] = {
        { 1, 0x0EF5E, 0x0B5A6D35, 0xE066175D },   // m0004_ride_dragon_lower b7 target_hash
        { 1, 0x1085A, 0x0B5A6D35, 0xE066175D },   // m0004_ride_dragon_lower b130 target_hash
        { 2, 0x0C36C, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b14 target_hash
        { 2, 0x0C370, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b14 target_hash2
        { 2, 0x0C4A4, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b20 target_hash
        { 2, 0x0C4A8, 0x082F0420, 0xE066175D },   // m0004_ride_dragon_upper b20 target_hash2
        { 2, 0x0C4D8, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b21 target_hash
        { 2, 0x0C4DC, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b21 target_hash2
        { 2, 0x0C5E0, 0x117F8F51, 0xE066175D },   // m0004_ride_dragon_upper b26 target_hash2
        { 2, 0x0C678, 0xE3F3D49B, 0xE066175D },   // m0004_ride_dragon_upper b29 target_hash
        { 2, 0x0C67C, 0xE3F3D49B, 0xE066175D },   // m0004_ride_dragon_upper b29 target_hash2
        { 2, 0x0C6E0, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b31 target_hash
        { 2, 0x0C6E4, 0x082F0420, 0xE066175D },   // m0004_ride_dragon_upper b31 target_hash2
        { 2, 0x0C748, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b33 target_hash
        { 2, 0x0C880, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b39 target_hash
        { 2, 0x0D1D8, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b85 target_hash
        { 2, 0x0D1DC, 0x117F8F51, 0xE066175D },   // m0004_ride_dragon_upper b85 target_hash2
        { 2, 0x0D20C, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b86 target_hash
        { 2, 0x0D210, 0x082F0420, 0xE066175D },   // m0004_ride_dragon_upper b86 target_hash2
        { 2, 0x0D240, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b87 target_hash
        { 2, 0x0D244, 0xF5150415, 0xE066175D },   // m0004_ride_dragon_upper b87 target_hash2
    };
}
