#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/ik_patches.py from the Wyvern's
// charts (build 1.0.0.2976). The aim IK's reference bone is B_Body_00, which
// the broom has, instead of the Wyvern's B_IK_Head_00, and the flight idle's
// aim turns the broom to the camera over about two seconds.
namespace bm::broomchart
{
    inline constexpr HoverPatch kIkPatches[] = {
        { 0, 0x221BF, 0x4B495F42, 0x6F425F42 },   // m0004_dragon_upper: B_IK_Head_00 -> B_Body_00, bytes 0-3
        { 0, 0x221C3, 0x6165485F, 0x305F7964 },   // m0004_dragon_upper: B_IK_Head_00 -> B_Body_00, bytes 4-7
        { 0, 0x221C7, 0x30305F64, 0x00000030 },   // m0004_dragon_upper: B_IK_Head_00 -> B_Body_00, bytes 8-11
        { 2, 0x074D3, 0x4B495F42, 0x6F425F42 },   // m0004_ride_dragon_upper: B_IK_Head_00 -> B_Body_00, bytes 0-3
        { 2, 0x074D7, 0x6165485F, 0x305F7964 },   // m0004_ride_dragon_upper: B_IK_Head_00 -> B_Body_00, bytes 4-7
        { 2, 0x074DB, 0x30305F64, 0x00000030 },   // m0004_ride_dragon_upper: B_IK_Head_00 -> B_Body_00, bytes 8-11
        { 2, 0x101FF, 0x40C00000, 0x3F800000 },   // m0004_ride_dragon_upper: E066175D aim rate 6 -> 1
    };
}
