#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/mount_patches.py from the Wyvern's
// RideOn chart (build 1.0.0.2976). Mounting finishes by itself one second
// in, as it did when X was pressed, before the shared list unmounts Kliff.
namespace bm::broomchart
{
    inline constexpr HoverPatch kMountPatches[] = {
        { 2, 0x0C4B8, 0x01000000, 0x00000000 },   // m0004_ride_dragon_upper b20: no key to finish mounting
        { 2, 0x00EF0, 0x408AAAAB, 0x3F800000 },   // m0004_ride_dragon_upper 51015354 window opens at 1.00 s, was 4.33
        { 2, 0x00D2C, 0x40155556, 0x3F800000 },   // m0004_ride_dragon_upper B9B79B01 window opens at 1.00 s, was 2.33
    };
}
