#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/quiet_patches.py from the Wyvern's
// charts (build 1.0.0.2976). Frame events whose hash only the Wyvern's family
// of charts uses (its wing beats, breathing and calls) get the hash zeroed.
namespace bm::broomchart
{
    inline constexpr HoverPatch kQuietPatches[] = {
        { 0, 0x334BF, 0xCD752D34, 0x00000000 },   // m0004_dragon_upper event 5 type 42
        { 0, 0x3369B, 0x8A405F65, 0x00000000 },   // m0004_dragon_upper event 78 type 41
        { 0, 0x33827, 0xF2A1900A, 0x00000000 },   // m0004_dragon_upper event 177 type 41
        { 0, 0x3390F, 0xB469F23E, 0x00000000 },   // m0004_dragon_upper event 235 type 41
        { 0, 0x3393F, 0xCD752D34, 0x00000000 },   // m0004_dragon_upper event 293 type 42
        { 0, 0x33A6B, 0x062B2262, 0x00000000 },   // m0004_dragon_upper event 322 type 41
        { 0, 0x33D7B, 0x3C84EAA0, 0x00000000 },   // m0004_dragon_upper event 518 type 41
        { 0, 0x33DAB, 0xCD752D34, 0x00000000 },   // m0004_dragon_upper event 576 type 42
        { 0, 0x345C3, 0x85B92E45, 0x00000000 },   // m0004_dragon_upper event 1048 type 41
        { 0, 0x346DB, 0x63FCAA74, 0x00000000 },   // m0004_dragon_upper event 1118 type 41
        { 0, 0x3495F, 0x0BEAD16E, 0x00000000 },   // m0004_dragon_upper event 1279 type 41
        { 0, 0x34ABF, 0x4C137096, 0x00000000 },   // m0004_dragon_upper event 1367 type 41
        { 0, 0x34BA7, 0x71C1FEDA, 0x00000000 },   // m0004_dragon_upper event 1425 type 41
        { 0, 0x34C8F, 0x5895E721, 0x00000000 },   // m0004_dragon_upper event 1483 type 41
        { 0, 0x350F7, 0xCD752D34, 0x00000000 },   // m0004_dragon_upper event 1811 type 42
        { 0, 0x35223, 0x1BA9C3D6, 0x00000000 },   // m0004_dragon_upper event 1840 type 41
        { 0, 0x353C7, 0x2442D90D, 0x00000000 },   // m0004_dragon_upper event 1945 type 41
        { 0, 0x35EAF, 0x78803880, 0x00000000 },   // m0004_dragon_upper event 2643 type 41
        { 0, 0x35F97, 0xBA7AAAE2, 0x00000000 },   // m0004_dragon_upper event 2701 type 41
        { 0, 0x360AF, 0xCD752D34, 0x00000000 },   // m0004_dragon_upper event 2817 type 42
        { 0, 0x3607F, 0xEAAB79D7, 0x00000000 },   // m0004_dragon_upper event 2759 type 41
        { 0, 0x3657B, 0xBD992FE1, 0x00000000 },   // m0004_dragon_upper event 3078 type 41
        { 0, 0x36663, 0xE2C370B8, 0x00000000 },   // m0004_dragon_upper event 3136 type 41
        { 0, 0x3674B, 0x12A4BA8F, 0x00000000 },   // m0004_dragon_upper event 3194 type 41
        { 0, 0x36833, 0x708C4105, 0x00000000 },   // m0004_dragon_upper event 3252 type 41
        { 0, 0x3691B, 0x534CEDC3, 0x00000000 },   // m0004_dragon_upper event 3310 type 41
        { 0, 0x37203, 0x4C137096, 0x00000000 },   // m0004_dragon_upper event 3880 type 41
        { 0, 0x3711B, 0xF3C5CBE3, 0x00000000 },   // m0004_dragon_upper event 3822 type 41
        { 0, 0x37313, 0x9B592FCD, 0x00000000 },   // m0004_dragon_upper event 3948 type 41
        { 0, 0x37343, 0xCD752D34, 0x00000000 },   // m0004_dragon_upper event 4006 type 42
        { 0, 0x3746F, 0x53FA1CB0, 0x00000000 },   // m0004_dragon_upper event 4035 type 41
        { 0, 0x37C37, 0xFCF4A746, 0x00000000 },   // m0004_dragon_upper event 4533 type 41
        { 0, 0x37D73, 0x4C137096, 0x00000000 },   // m0004_dragon_upper event 4612 type 41
        { 0, 0x38A9B, 0x35C9BED7, 0x00000000 },   // m0004_dragon_upper event 5454 type 41
        { 0, 0x389B3, 0xF5BB27EF, 0x00000000 },   // m0004_dragon_upper event 5396 type 41
        { 0, 0x39263, 0xBFA03B21, 0x00000000 },   // m0004_dragon_upper event 5952 type 41
        { 0, 0x3934B, 0x5895E721, 0x00000000 },   // m0004_dragon_upper event 6010 type 41
        { 0, 0x3951B, 0xB469F23E, 0x00000000 },   // m0004_dragon_upper event 6126 type 41
        { 0, 0x3917B, 0x2442D90D, 0x00000000 },   // m0004_dragon_upper event 5894 type 41
        { 0, 0x39433, 0xBFA03B21, 0x00000000 },   // m0004_dragon_upper event 6068 type 41
        { 0, 0x39603, 0x71C1FEDA, 0x00000000 },   // m0004_dragon_upper event 6184 type 41
        { 0, 0x398BB, 0x4C137096, 0x00000000 },   // m0004_dragon_upper event 6358 type 41
        { 0, 0x396EB, 0x7B14B14E, 0x00000000 },   // m0004_dragon_upper event 6242 type 41
        { 0, 0x399A3, 0x35C9BED7, 0x00000000 },   // m0004_dragon_upper event 6416 type 41
        { 0, 0x397D3, 0xF3C5CBE3, 0x00000000 },   // m0004_dragon_upper event 6300 type 41
        { 0, 0x39A8B, 0xE4FAAD6C, 0x00000000 },   // m0004_dragon_upper event 6474 type 41
        { 0, 0x39B73, 0x14A8B306, 0x00000000 },   // m0004_dragon_upper event 6532 type 41
        { 0, 0x3A857, 0xCB3DBBA6, 0x00000000 },   // m0004_dragon_upper event 7357 type 41
        { 0, 0x3A76F, 0xB8078735, 0x00000000 },   // m0004_dragon_upper event 7299 type 41
        { 0, 0x3AC77, 0xC2F3970A, 0x00000000 },   // m0004_dragon_upper event 7621 type 41
        { 0, 0x3B1A3, 0x88C16084, 0x00000000 },   // m0004_dragon_upper event 7952 type 41
        { 0, 0x3B28B, 0xE78B6146, 0x00000000 },   // m0004_dragon_upper event 8010 type 41
        { 0, 0x3B37F, 0x2F4B2584, 0x00000000 },   // m0004_dragon_upper event 8071 type 41
        { 1, 0x13AC5, 0xF2A1900A, 0x00000000 },   // m0004_ride_dragon_lower event 5 type 41
        { 1, 0x13C45, 0xF5BB27EF, 0x00000000 },   // m0004_ride_dragon_lower event 101 type 41
        { 1, 0x14329, 0x2442D90D, 0x00000000 },   // m0004_ride_dragon_lower event 542 type 41
        { 1, 0x14775, 0x2442D90D, 0x00000000 },   // m0004_ride_dragon_lower event 817 type 41
        { 1, 0x15749, 0x2442D90D, 0x00000000 },   // m0004_ride_dragon_lower event 1830 type 41
        { 1, 0x15831, 0x119F36F9, 0x00000000 },   // m0004_ride_dragon_lower event 1888 type 41
        { 1, 0x15919, 0xB469F23E, 0x00000000 },   // m0004_ride_dragon_lower event 1946 type 41
        { 1, 0x15FA9, 0xFCF4A746, 0x00000000 },   // m0004_ride_dragon_lower event 2366 type 41
        { 1, 0x16091, 0x03C2F8C4, 0x00000000 },   // m0004_ride_dragon_lower event 2424 type 41
        { 1, 0x16179, 0xF5BB27EF, 0x00000000 },   // m0004_ride_dragon_lower event 2482 type 41
        { 1, 0x16261, 0xF5BB27EF, 0x00000000 },   // m0004_ride_dragon_lower event 2540 type 41
        { 1, 0x16349, 0x4C137096, 0x00000000 },   // m0004_ride_dragon_lower event 2598 type 41
        { 1, 0x164CD, 0x0BEAD16E, 0x00000000 },   // m0004_ride_dragon_lower event 2695 type 41
        { 1, 0x16B85, 0x6EA74CE1, 0x00000000 },   // m0004_ride_dragon_lower event 3125 type 41
        { 1, 0x170E5, 0x302269EF, 0x00000000 },   // m0004_ride_dragon_lower event 3469 type 41
        { 1, 0x171CD, 0x6EA74CE1, 0x00000000 },   // m0004_ride_dragon_lower event 3527 type 41
        { 1, 0x17329, 0x099C0ADC, 0x00000000 },   // m0004_ride_dragon_lower event 3614 type 41
        { 1, 0x17411, 0x2829BFC4, 0x00000000 },   // m0004_ride_dragon_lower event 3672 type 41
        { 1, 0x17531, 0x863E32D6, 0x00000000 },   // m0004_ride_dragon_lower event 3744 type 41
        { 1, 0x1776D, 0xBFA03B21, 0x00000000 },   // m0004_ride_dragon_lower event 3887 type 41
        { 2, 0x0F41F, 0x4C137096, 0x00000000 },   // m0004_ride_dragon_upper event 110 type 41
        { 2, 0x0F337, 0x2442D90D, 0x00000000 },   // m0004_ride_dragon_upper event 52 type 41
        { 2, 0x0F507, 0x71C1FEDA, 0x00000000 },   // m0004_ride_dragon_upper event 168 type 41
        { 2, 0x0F5EF, 0x5895E721, 0x00000000 },   // m0004_ride_dragon_upper event 226 type 41
        { 2, 0x0FD5B, 0xF5BB27EF, 0x00000000 },   // m0004_ride_dragon_upper event 701 type 41
        { 2, 0x0FE43, 0xF2A1900A, 0x00000000 },   // m0004_ride_dragon_upper event 759 type 41
        { 2, 0x0FF3F, 0x2442D90D, 0x00000000 },   // m0004_ride_dragon_upper event 822 type 41
        { 2, 0x101C3, 0xF3C5CBE3, 0x00000000 },   // m0004_ride_dragon_upper event 983 type 41
        { 2, 0x1055F, 0xA560F6E1, 0x00000000 },   // m0004_ride_dragon_upper event 1214 type 41
        { 2, 0x10843, 0xCD752D34, 0x00000000 },   // m0004_ride_dragon_upper event 1445 type 42
        { 2, 0x10C23, 0x337B8F0D, 0x00000000 },   // m0004_ride_dragon_upper event 1647 type 41
        { 2, 0x10D0B, 0x7B14B14E, 0x00000000 },   // m0004_ride_dragon_upper event 1705 type 41
        { 2, 0x10F7F, 0x9F9F15E5, 0x00000000 },   // m0004_ride_dragon_upper event 1862 type 41
        { 2, 0x11E77, 0x4C137096, 0x00000000 },   // m0004_ride_dragon_upper event 2820 type 41
        { 2, 0x12043, 0x4C137096, 0x00000000 },   // m0004_ride_dragon_upper event 2935 type 41
        { 2, 0x1212B, 0xB469F23E, 0x00000000 },   // m0004_ride_dragon_upper event 2993 type 41
        { 2, 0x135A7, 0x14A8B306, 0x00000000 },   // m0004_ride_dragon_upper event 4304 type 41
        { 2, 0x1368F, 0xA8C82053, 0x00000000 },   // m0004_ride_dragon_upper event 4362 type 41
        { 2, 0x13777, 0x9942467A, 0x00000000 },   // m0004_ride_dragon_upper event 4420 type 41
        { 2, 0x1385F, 0x129B7C1E, 0x00000000 },   // m0004_ride_dragon_upper event 4478 type 41
        { 2, 0x14B3F, 0xE7BBA24C, 0x00000000 },   // m0004_ride_dragon_upper event 5686 type 41
        { 2, 0x14C63, 0xF3C5CBE3, 0x00000000 },   // m0004_ride_dragon_upper event 5759 type 41
    };
}
