#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/rideon_blend_patches.py from the
// Wyvern's RideOn chart (build 1.0.0.2976). Its flight nodes play the blend
// instead of a fixed clip, so both of Broomy's layers pitch with the flight.
namespace bm::broomchart
{
    inline constexpr HoverPatch kRideOnBlendPatches[] = {
        { 2, 0x01C84, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper E066175D cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x01F76, 0xFFFFFFFF, 0x0001FFFF },   // m0004_ride_dragon_upper E066175D cd_rd_wyvern_basic_00_00_air_std_idle_00
        { 2, 0x02FA8, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper 52D7F8A5 cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x03092, 0xFFFFFFFF, 0x0001FFFF },   // m0004_ride_dragon_upper 52D7F8A5 cd_rd_wyvern_basic_00_00_nor_move_walk_f_ing_00
        { 2, 0x02DE8, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper 6272DA7B cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x02ED2, 0xFFFFFFFF, 0x0001FFFF },   // m0004_ride_dragon_upper 6272DA7B cd_rd_wyvern_basic_00_00_nor_move_walk_f_ing_00
        { 2, 0x024D8, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper 87CB4170 cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x020AE, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper 8767D78A cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x023A0, 0xFFFFFFFF, 0x0001FFFF },   // m0004_ride_dragon_upper 8767D78A cd_rd_wyvern_basic_00_00_air_std_idle_00
        { 2, 0x028F8, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper B8A26CDD cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x02A2A, 0xFFFFFFFF, 0x0001FFFF },   // m0004_ride_dragon_upper B8A26CDD cd_rd_wyvern_basic_00_00_air_move_walk_f_ing_00
        { 2, 0x02B70, 0xFFFFFFFF, 0x0000FFFF },   // m0004_ride_dragon_upper 0DCF66F2 cd_dragon_basic_00_00_air_move_fly_walk_f_ing_00
        { 2, 0x02CA2, 0xFFFFFFFF, 0x0001FFFF },   // m0004_ride_dragon_upper 0DCF66F2 cd_rd_wyvern_basic_00_00_air_move_walk_f_ing_00
    };
}
