#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/right_mount_patches.py from the
// Wyvern's RideOn chart (build 1.0.0.2976). The fireball action A8 becomes
// a copy of the mount action keyed by Broom_Ride's right pivot (262C63D3),
// so Kliff can mount from either side.
namespace bm::broomchart
{
    inline constexpr HoverPatch kRightMountPatches[] = {
        { 2, 0x07DDA, 0x00000809, 0x00008101 },   // m0004_ride_dragon_upper A8 word +0x08 -> A63's
        { 2, 0x07DDE, 0x60000100, 0x00000000 },   // m0004_ride_dragon_upper A8 word +0x0C -> A63's
        { 2, 0x07DEA, 0x2AB02983, 0x262C63D3 },   // m0004_ride_dragon_upper A8 key -> A63's
        { 2, 0x07E26, 0x0000002E, 0x00000007 },   // m0004_ride_dragon_upper A8 word +0x54 -> A63's
        { 2, 0x07E56, 0x43480000, 0xBF800000 },   // m0004_ride_dragon_upper A8 word +0x84 -> A63's
        { 2, 0x07E76, 0x00002F1C, 0x00002EE1 },   // m0004_ride_dragon_upper A8 word +0xA4 -> A63's
        { 2, 0x07E8A, 0x00000003, 0x00000004 },   // m0004_ride_dragon_upper A8 word +0xB8 -> A63's
        { 2, 0x07EB2, 0xFFFF0080, 0xFFFF002A },   // m0004_ride_dragon_upper A8 word +0xE0 -> A63's
        { 2, 0x07EB6, 0xFFFF0001, 0xFFFF0002 },   // m0004_ride_dragon_upper A8 word +0xE4 -> A63's
        { 2, 0x07EBE, 0x0B050000, 0x0B020002 },   // m0004_ride_dragon_upper A8 word +0xEC -> A63's
        { 2, 0x07EC2, 0x0700070C, 0x0300070C },   // m0004_ride_dragon_upper A8 word +0xF0 -> A63's
        { 2, 0x07ECA, 0xFF0000FF, 0xFF0003FF },   // m0004_ride_dragon_upper A8 word +0xF8 -> A63's
        { 2, 0x07ECE, 0x01040500, 0x01040503 },   // m0004_ride_dragon_upper A8 word +0xFC -> A63's
        { 2, 0x07EDA, 0x85C80000, 0x85A84400 },   // m0004_ride_dragon_upper A8 word +0x108 -> A63's
        { 2, 0x07EDE, 0x0B000010, 0x0B000000 },   // m0004_ride_dragon_upper A8 word +0x10C -> A63's
    };
}
