#pragma once
#include <cstdint>

// Generated by private/research/newmount/speed_patches.py from the Wyvern's
// riding charts (build 1.0.0.2976). Each entry is a Wyvern speed the
// plugin multiplies by the ini's percentage for its kind.
namespace bm::broomchart
{
    enum SpeedKind : uint8_t { kGroundSpeed, kFlightSpeed, kBoostSpeed, kClimbSpeed, kNoClimb };

    struct SpeedPatch
    {
        uint8_t chart;
        uint32_t at;
        uint32_t wyvern;
        SpeedKind kind;
    };

    inline constexpr SpeedPatch kSpeedPatches[] = {
        { 1, 0x00520, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 4 move word 7: 5
        { 1, 0x00578, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 4 vertical word 3: 20
        { 1, 0x006DC, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 5 move word 7: 5
        { 1, 0x00734, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 5 vertical word 3: 20
        { 1, 0x00998, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 6 move word 7: 5
        { 1, 0x009F0, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 6 vertical word 3: 20
        { 1, 0x00B54, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 7 move word 7: 5
        { 1, 0x00BAC, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 7 vertical word 3: 20
        { 1, 0x00E10, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 8 move word 7: 5
        { 1, 0x00E64, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 8 vertical word 2: 5
        { 1, 0x00E68, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 8 vertical word 3: 20
        { 1, 0x00FCC, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 9 move word 7: 5
        { 1, 0x01020, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 9 vertical word 2: 5
        { 1, 0x01024, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 9 vertical word 3: 20
        { 1, 0x01284, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 10 move word 6: 25
        { 1, 0x01288, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 10 move word 7: 25
        { 1, 0x012B4, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 10 move word 18: 40
        { 1, 0x014C6, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 11 move word 6: 20
        { 1, 0x014CA, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 11 move word 7: 20
        { 1, 0x014F6, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 11 move word 18: 30
        { 1, 0x016E0, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 12 move word 6: 25
        { 1, 0x016E4, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 12 move word 7: 25
        { 1, 0x01710, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 12 move word 18: 40
        { 1, 0x0193A, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 13 move word 6: 20
        { 1, 0x0193E, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 13 move word 7: 20
        { 1, 0x0196A, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 13 move word 18: 30
        { 1, 0x01B6C, 0x41C80000, kBoostSpeed },   // m0004_ride_dragon_lower node 14 move word 6: 25
        { 1, 0x01B70, 0x41C80000, kBoostSpeed },   // m0004_ride_dragon_lower node 14 move word 7: 25
        { 1, 0x01B9C, 0x42200000, kBoostSpeed },   // m0004_ride_dragon_lower node 14 move word 18: 40
        { 1, 0x01BC4, 0x41A00000, kNoClimb },   // m0004_ride_dragon_lower node 14 vertical word 2: 20
        { 1, 0x01DC6, 0x41A00000, kBoostSpeed },   // m0004_ride_dragon_lower node 15 move word 6: 20
        { 1, 0x01DCA, 0x41A00000, kBoostSpeed },   // m0004_ride_dragon_lower node 15 move word 7: 20
        { 1, 0x01DF6, 0x41F00000, kBoostSpeed },   // m0004_ride_dragon_lower node 15 move word 18: 30
        { 1, 0x01E1E, 0x41A00000, kNoClimb },   // m0004_ride_dragon_lower node 15 vertical word 2: 20
        { 1, 0x01FF8, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 16 move word 6: 25
        { 1, 0x01FFC, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 16 move word 7: 25
        { 1, 0x02028, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 16 move word 18: 40
        { 1, 0x02054, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 16 vertical word 3: 20
        { 1, 0x02252, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 17 move word 6: 20
        { 1, 0x02256, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 17 move word 7: 20
        { 1, 0x02282, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 17 move word 18: 30
        { 1, 0x022AE, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 17 vertical word 3: 20
        { 1, 0x02484, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 18 move word 6: 25
        { 1, 0x02488, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 18 move word 7: 25
        { 1, 0x024B4, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 18 move word 18: 40
        { 1, 0x024E0, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 18 vertical word 3: 20
        { 1, 0x02654, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 19 move word 6: 20
        { 1, 0x02658, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 19 move word 7: 20
        { 1, 0x02684, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 19 move word 18: 30
        { 1, 0x026B0, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 19 vertical word 3: 20
        { 1, 0x02824, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 20 move word 6: 25
        { 1, 0x02828, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 20 move word 7: 25
        { 1, 0x02854, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 20 move word 18: 40
        { 1, 0x0287C, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 20 vertical word 2: 5
        { 1, 0x02880, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 20 vertical word 3: 20
        { 1, 0x02A7E, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 21 move word 6: 20
        { 1, 0x02A82, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 21 move word 7: 20
        { 1, 0x02AAE, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 21 move word 18: 30
        { 1, 0x02AD6, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 21 vertical word 2: 5
        { 1, 0x02ADA, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 21 vertical word 3: 20
        { 1, 0x02CB0, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 22 move word 6: 20
        { 1, 0x02CB4, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 22 move word 7: 20
        { 1, 0x02EF2, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 23 move word 6: 10
        { 1, 0x02EF6, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 23 move word 7: 20
        { 1, 0x0310C, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 24 move word 6: 20
        { 1, 0x03110, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 24 move word 7: 20
        { 1, 0x03164, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 24 vertical word 2: 5
        { 1, 0x03168, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 24 vertical word 3: 20
        { 1, 0x03366, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 25 move word 6: 10
        { 1, 0x0336A, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 25 move word 7: 20
        { 1, 0x033BE, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 25 vertical word 2: 5
        { 1, 0x033C2, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 25 vertical word 3: 20
        { 1, 0x03598, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 26 move word 6: 20
        { 1, 0x0359C, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 26 move word 7: 20
        { 1, 0x037DA, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 27 move word 6: 10
        { 1, 0x037DE, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 27 move word 7: 20
        { 1, 0x039F4, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 28 move word 6: 20
        { 1, 0x039F8, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 28 move word 7: 20
        { 1, 0x03A4C, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 28 vertical word 2: 5
        { 1, 0x03A50, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 28 vertical word 3: 20
        { 1, 0x03C4E, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 29 move word 6: 10
        { 1, 0x03C52, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 29 move word 7: 20
        { 1, 0x03CA6, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 29 vertical word 2: 5
        { 1, 0x03CAA, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 29 vertical word 3: 20
        { 1, 0x03E80, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 30 move word 6: 15
        { 1, 0x03E84, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 30 move word 7: 10
        { 1, 0x04176, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 31 move word 6: 10
        { 1, 0x0417A, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 31 move word 7: 10
        { 1, 0x042F0, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 32 move word 6: 15
        { 1, 0x042F4, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 32 move word 7: 10
        { 1, 0x04348, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 32 vertical word 2: 5
        { 1, 0x0434C, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 32 vertical word 3: 20
        { 1, 0x0454A, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 33 move word 6: 10
        { 1, 0x0454E, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 33 move word 7: 10
        { 1, 0x045A2, 0x40A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 33 vertical word 2: 5
        { 1, 0x045A6, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_lower node 33 vertical word 3: 20
        { 1, 0x0477C, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 34 move word 6: 25
        { 1, 0x04780, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 34 move word 7: 25
        { 1, 0x047AC, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 34 move word 18: 40
        { 1, 0x04934, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 35 move word 6: 20
        { 1, 0x04938, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 35 move word 7: 20
        { 1, 0x04964, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 35 move word 18: 30
        { 1, 0x04AEC, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 36 move word 6: 25
        { 1, 0x04AF0, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 36 move word 7: 25
        { 1, 0x04B1C, 0x42200000, kFlightSpeed },   // m0004_ride_dragon_lower node 36 move word 18: 40
        { 1, 0x04CBC, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 37 move word 6: 20
        { 1, 0x04CC0, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 37 move word 7: 20
        { 1, 0x04CEC, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 37 move word 18: 30
        { 1, 0x04E90, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 38 move word 7: 25
        { 1, 0x05176, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 39 move word 7: 25
        { 1, 0x0544C, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 40 move word 6: 10
        { 1, 0x05450, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 40 move word 7: 15
        { 1, 0x054A4, 0x42480000, kClimbSpeed },   // m0004_ride_dragon_lower node 40 vertical word 2: 50
        { 1, 0x054BC, 0x42C80000, kClimbSpeed },   // m0004_ride_dragon_lower node 40 vertical word 2: 100
        { 1, 0x054C0, 0x43160000, kClimbSpeed },   // m0004_ride_dragon_lower node 40 vertical word 3: 150
        { 1, 0x055F8, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 41 move word 6: 10
        { 1, 0x055FC, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 41 move word 7: 15
        { 1, 0x05650, 0x42480000, kClimbSpeed },   // m0004_ride_dragon_lower node 41 vertical word 2: 50
        { 1, 0x05668, 0x42C80000, kClimbSpeed },   // m0004_ride_dragon_lower node 41 vertical word 2: 100
        { 1, 0x0566C, 0x43160000, kClimbSpeed },   // m0004_ride_dragon_lower node 41 vertical word 3: 150
        { 1, 0x057BC, 0x42700000, kFlightSpeed },   // m0004_ride_dragon_lower node 42 move word 6: 60
        { 1, 0x057C0, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 42 move word 7: 15
        { 1, 0x05824, 0x42C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 42 move word 6: 100
        { 1, 0x05828, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 42 move word 7: 30
        { 1, 0x0588C, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 42 move word 6: 20
        { 1, 0x05890, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 42 move word 7: 80
        { 1, 0x058E8, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 42 vertical word 3: 30
        { 1, 0x05B24, 0x42700000, kFlightSpeed },   // m0004_ride_dragon_lower node 43 move word 6: 60
        { 1, 0x05B28, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 43 move word 7: 15
        { 1, 0x05B8C, 0x42C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 43 move word 6: 100
        { 1, 0x05B90, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 43 move word 7: 30
        { 1, 0x05BF4, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 43 move word 6: 20
        { 1, 0x05BF8, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 43 move word 7: 80
        { 1, 0x05C50, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 43 vertical word 3: 30
        { 1, 0x05E8C, 0x42700000, kFlightSpeed },   // m0004_ride_dragon_lower node 44 move word 6: 60
        { 1, 0x05E90, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 44 move word 7: 15
        { 1, 0x05EF4, 0x42C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 44 move word 6: 100
        { 1, 0x05EF8, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 44 move word 7: 30
        { 1, 0x05F5C, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 44 move word 6: 20
        { 1, 0x05F60, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 44 move word 7: 80
        { 1, 0x05FB8, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 44 vertical word 3: 30
        { 1, 0x061F4, 0x42700000, kFlightSpeed },   // m0004_ride_dragon_lower node 45 move word 6: 60
        { 1, 0x061F8, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 45 move word 7: 15
        { 1, 0x0625C, 0x42C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 45 move word 6: 100
        { 1, 0x06260, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 45 move word 7: 30
        { 1, 0x062C4, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 45 move word 6: 20
        { 1, 0x062C8, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 45 move word 7: 80
        { 1, 0x06320, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 45 vertical word 3: 30
        { 1, 0x06524, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 46 move word 6: 10
        { 1, 0x06528, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 46 move word 7: 20
        { 1, 0x06580, 0x42480000, kClimbSpeed },   // m0004_ride_dragon_lower node 46 vertical word 3: 50
        { 1, 0x066C0, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 47 move word 6: 10
        { 1, 0x066C4, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 47 move word 7: 20
        { 1, 0x0671C, 0x42480000, kClimbSpeed },   // m0004_ride_dragon_lower node 47 vertical word 3: 50
        { 1, 0x06860, 0x42700000, kFlightSpeed },   // m0004_ride_dragon_lower node 48 move word 7: 60
        { 1, 0x068C4, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 48 move word 6: 15
        { 1, 0x068C8, 0x43FA0000, kFlightSpeed },   // m0004_ride_dragon_lower node 48 move word 7: 500
        { 1, 0x06930, 0x42C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 48 move word 7: 100
        { 1, 0x06988, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 48 vertical word 3: 30
        { 1, 0x06A8E, 0x42700000, kFlightSpeed },   // m0004_ride_dragon_lower node 49 move word 7: 60
        { 1, 0x06AF2, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 49 move word 6: 15
        { 1, 0x06AF6, 0x43FA0000, kFlightSpeed },   // m0004_ride_dragon_lower node 49 move word 7: 500
        { 1, 0x06B5E, 0x42C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 49 move word 7: 100
        { 1, 0x06BB6, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 49 vertical word 3: 30
        { 1, 0x06CAC, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 50 vertical word 3: 30
        { 1, 0x06DA2, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 51 vertical word 3: 30
        { 1, 0x06F00, 0x42C80000, kClimbSpeed },   // m0004_ride_dragon_lower node 52 vertical word 3: 100
        { 1, 0x0734E, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 55 move word 6: 10
        { 1, 0x07352, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 55 move word 7: 20
        { 1, 0x073B6, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 55 move word 6: 25
        { 1, 0x073BA, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 55 move word 7: 25
        { 1, 0x0740E, 0x42B40000, kClimbSpeed },   // m0004_ride_dragon_lower node 55 vertical word 2: 90
        { 1, 0x07412, 0x42700000, kClimbSpeed },   // m0004_ride_dragon_lower node 55 vertical word 3: 60
        { 1, 0x07426, 0x41700000, kClimbSpeed },   // m0004_ride_dragon_lower node 55 vertical word 2: 15
        { 1, 0x0742A, 0x42C80000, kClimbSpeed },   // m0004_ride_dragon_lower node 55 vertical word 3: 100
        { 1, 0x075C6, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_lower node 56 move word 6: 10
        { 1, 0x075CA, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 56 move word 7: 15
        { 1, 0x0762E, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 56 move word 6: 20
        { 1, 0x07632, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 56 move word 7: 20
        { 1, 0x07686, 0x41900000, kClimbSpeed },   // m0004_ride_dragon_lower node 56 vertical word 2: 18
        { 1, 0x0768A, 0x42700000, kClimbSpeed },   // m0004_ride_dragon_lower node 56 vertical word 3: 60
        { 1, 0x0769E, 0x41200000, kClimbSpeed },   // m0004_ride_dragon_lower node 56 vertical word 2: 10
        { 1, 0x076A2, 0x42C80000, kClimbSpeed },   // m0004_ride_dragon_lower node 56 vertical word 3: 100
        { 1, 0x07864, 0x40B33333, kGroundSpeed },   // m0004_ride_dragon_lower node 57 move word 6: 5.6
        { 1, 0x07868, 0x41A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 57 move word 7: 20
        { 1, 0x07AE2, 0x40800000, kGroundSpeed },   // m0004_ride_dragon_lower node 58 move word 6: 4
        { 1, 0x07AE6, 0x41A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 58 move word 7: 20
        { 1, 0x07C24, 0x40400000, kGroundSpeed },   // m0004_ride_dragon_lower node 59 move word 7: 3
        { 1, 0x07EA2, 0x40400000, kGroundSpeed },   // m0004_ride_dragon_lower node 60 move word 7: 3
        { 1, 0x07FDC, 0x41300000, kGroundSpeed },   // m0004_ride_dragon_lower node 61 move word 6: 11
        { 1, 0x07FE0, 0x41A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 61 move word 7: 20
        { 1, 0x0825A, 0x40E00000, kGroundSpeed },   // m0004_ride_dragon_lower node 62 move word 6: 7
        { 1, 0x0825E, 0x41A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 62 move word 7: 20
        { 1, 0x0839C, 0x40A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 63 move word 7: 5
        { 1, 0x0857A, 0x40A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 64 move word 7: 5
        { 1, 0x086B4, 0x41200000, kGroundSpeed },   // m0004_ride_dragon_lower node 65 move word 6: 10
        { 1, 0x086B8, 0x41A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 65 move word 7: 20
        { 1, 0x087F6, 0x40A00000, kGroundSpeed },   // m0004_ride_dragon_lower node 66 move word 7: 5
        { 1, 0x08930, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 67 move word 6: 50
        { 1, 0x08934, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 67 move word 7: 25
        { 1, 0x08AE8, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 68 move word 6: 50
        { 1, 0x08AEC, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 68 move word 7: 25
        { 1, 0x08CA0, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 69 move word 6: 50
        { 1, 0x08CA4, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 69 move word 7: 50
        { 1, 0x08E44, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 70 move word 6: 50
        { 1, 0x08E48, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 70 move word 7: 50
        { 1, 0x08FE0, 0x40400000, kFlightSpeed },   // m0004_ride_dragon_lower node 71 move word 7: 3
        { 1, 0x09038, 0x43480000, kClimbSpeed },   // m0004_ride_dragon_lower node 71 vertical word 3: 200
        { 1, 0x09170, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 72 move word 6: 25
        { 1, 0x09174, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 72 move word 7: 5
        { 1, 0x091CC, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 72 vertical word 3: 30
        { 1, 0x09498, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 73 move word 6: 50
        { 1, 0x09500, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 73 move word 6: 25
        { 1, 0x09504, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 73 move word 7: 15
        { 1, 0x0955C, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 73 vertical word 3: 30
        { 1, 0x09714, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 74 move word 6: 25
        { 1, 0x09718, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 74 move word 7: 15
        { 1, 0x09770, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 74 vertical word 3: 30
        { 1, 0x098B0, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 75 move word 6: 25
        { 1, 0x098B4, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 75 move word 7: 15
        { 1, 0x0990C, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 75 vertical word 3: 30
        { 1, 0x099FA, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 76 move word 6: 80
        { 1, 0x09A62, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 76 move word 6: 30
        { 1, 0x09A66, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 76 move word 7: 50
        { 1, 0x09ABE, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 76 vertical word 3: 30
        { 1, 0x09BE8, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 77 move word 6: 25
        { 1, 0x09BEC, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 77 move word 7: 15
        { 1, 0x09C44, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 77 vertical word 3: 30
        { 1, 0x09D84, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_lower node 78 move word 6: 25
        { 1, 0x09D88, 0x41700000, kFlightSpeed },   // m0004_ride_dragon_lower node 78 move word 7: 15
        { 1, 0x09DE0, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 78 vertical word 3: 30
        { 1, 0x09ECE, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_lower node 79 move word 6: 80
        { 1, 0x09F36, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_lower node 79 move word 6: 30
        { 1, 0x09F3A, 0x42480000, kFlightSpeed },   // m0004_ride_dragon_lower node 79 move word 7: 50
        { 1, 0x09F92, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_lower node 79 vertical word 3: 30
        { 2, 0x000D4, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 0 move word 6: 10
        { 2, 0x000D8, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 0 move word 7: 5
        { 2, 0x00130, 0x42B40000, kClimbSpeed },   // m0004_ride_dragon_upper node 0 vertical word 3: 90
        { 2, 0x002E4, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 1 move word 7: 5
        { 2, 0x0033C, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_upper node 1 vertical word 3: 20
        { 2, 0x009E6, 0x42480000, kGroundSpeed },   // m0004_ride_dragon_upper node 6 move word 6: 50
        { 2, 0x00A42, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_upper node 6 vertical word 3: 30
        { 2, 0x01CC4, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 24 move word 7: 5
        { 2, 0x020EE, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 26 move word 7: 5
        { 2, 0x02518, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 28 move word 7: 5
        { 2, 0x05058, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_upper node 59 move word 6: 30
        { 2, 0x0505C, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 59 move word 7: 5
        { 2, 0x050C0, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_upper node 59 move word 6: 30
        { 2, 0x050C4, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 59 move word 7: 20
        { 2, 0x05128, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 59 move word 6: 10
        { 2, 0x0512C, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 59 move word 7: 80
        { 2, 0x05184, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_upper node 59 vertical word 3: 30
        { 2, 0x05320, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_upper node 60 move word 6: 30
        { 2, 0x05388, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 60 move word 6: 10
        { 2, 0x0538C, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 60 move word 7: 10
        { 2, 0x0552A, 0x41C80000, kFlightSpeed },   // m0004_ride_dragon_upper node 61 move word 6: 25
        { 2, 0x0552E, 0x40A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 61 move word 7: 5
        { 2, 0x05592, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_upper node 61 move word 6: 30
        { 2, 0x05596, 0x41A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 61 move word 7: 20
        { 2, 0x055FA, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 61 move word 6: 10
        { 2, 0x055FE, 0x42A00000, kFlightSpeed },   // m0004_ride_dragon_upper node 61 move word 7: 80
        { 2, 0x05656, 0x41F00000, kClimbSpeed },   // m0004_ride_dragon_upper node 61 vertical word 3: 30
        { 2, 0x057F2, 0x41F00000, kFlightSpeed },   // m0004_ride_dragon_upper node 62 move word 6: 30
        { 2, 0x0585A, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 62 move word 6: 10
        { 2, 0x0585E, 0x41200000, kFlightSpeed },   // m0004_ride_dragon_upper node 62 move word 7: 10
        { 2, 0x059E0, 0x40A00000, kGroundSpeed },   // m0004_ride_dragon_upper node 63 move word 6: 5
        { 2, 0x059E4, 0x40A00000, kGroundSpeed },   // m0004_ride_dragon_upper node 63 move word 7: 5
        { 2, 0x05B5A, 0x41F00000, kGroundSpeed },   // m0004_ride_dragon_upper node 64 move word 6: 30
        { 2, 0x05BC2, 0x41200000, kGroundSpeed },   // m0004_ride_dragon_upper node 64 move word 6: 10
        { 2, 0x05BC6, 0x41200000, kGroundSpeed },   // m0004_ride_dragon_upper node 64 move word 7: 10
        { 2, 0x05D58, 0x41F00000, kGroundSpeed },   // m0004_ride_dragon_upper node 65 move word 6: 30
        { 2, 0x05DC0, 0x41200000, kGroundSpeed },   // m0004_ride_dragon_upper node 65 move word 6: 10
        { 2, 0x05DC4, 0x41200000, kGroundSpeed },   // m0004_ride_dragon_upper node 65 move word 7: 10
        { 2, 0x05F36, 0x41200000, kClimbSpeed },   // m0004_ride_dragon_upper node 66 vertical word 2: 10
        { 2, 0x05F3A, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_upper node 66 vertical word 3: 20
        { 2, 0x05F52, 0x41A00000, kClimbSpeed },   // m0004_ride_dragon_upper node 66 vertical word 3: 20
    };

    // The boost's nodes, by byte range in their chart.
    struct NodeRange
    {
        uint8_t chart;
        uint32_t begin;
        uint32_t end;
    };

    inline constexpr NodeRange kBoostNodes[] = {
        { 1, 0x01A9C, 0x01CF6 },   // m0004_ride_dragon_lower node 14
        { 1, 0x01CF6, 0x01F28 },   // m0004_ride_dragon_lower node 15
    };
}
