#pragma once

// Generated by speeder/pack_assets.py: the files the plugin hands the game
// for the speeder, each an RCDATA resource of the plugin (src/speeder.rc).
// A path no pack holds has a shipped file for the find and existence checks;
// one with no resource (0) loads that file as it is. Broomy serves the
// shared paths too, so the plugin leaves them to Broomy when it is there.
namespace bm::speederfiles
{
    struct File
    {
        const char* path;
        const char* standIn;
        int resource;
        bool shared;
    };

    inline constexpr File kFiles[] = {
        { "actionchart/bin__/animmeta/1_pc/1_phm/cd_phm_rd_orca_basic_00_00_nor_move_underwater_walkfast_f_ing_00.paa_metabin", nullptr, 201, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/cd_phm_rd_orca_basic_00_00_nor_std_underwater_idle_00.paa_metabin", nullptr, 202, false },
        { "character/bin__/prefab/2_mon/cd_m0004_00_dragon/cd_m0004_00_phoenix/cd_m0004_00_phoenix_00_0001.prefab", nullptr, 203, false },
        { "character/binary/motionblending/phm/orca_rider_move_ing.motionblending", nullptr, 204, false },
        { "character/binary/motionblending/speed_riding_move.motionblending", "character/binary/motionblending/broom_riding_move.motionblending", 205, false },
        { "character/model/4_riding/cd_r0032_00_broom/cd_r0032_00_speed_0001.pac", "character/model/4_riding/cd_r0032_00_broom/cd_r0032_00_broom_0001.pac", 206, false },
        { "character/modelproperty/4_riding/cd_r0032_00_broom/cd_r0032_00_speed_0001.pac_xml", "character/modelproperty/4_riding/cd_r0032_00_broom/cd_r0032_00_broom_0001.pac_xml", 207, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", nullptr, 208, true },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_run_f_ing_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 209, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_runfast_f_ing_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 210, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walk_f_ing_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 211, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 212, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 213, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_ing_00.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 214, false },
        { "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_std_idle_01.paa", "character/motion/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa", 215, false },
        { "character/motion/1_pc/1_phm/cd_phm_rd_orca_basic_00_00_nor_move_underwater_walkfast_f_ing_00.paa", nullptr, 216, false },
        { "character/motion/1_pc/1_phm/cd_phm_rd_orca_basic_00_00_nor_std_underwater_idle_00.paa", nullptr, 217, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_run_f_ing_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_run_f_ing_00.paa", 218, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_runfast_f_ing_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_runfast_f_ing_00.paa", 219, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walk_f_ing_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walk_f_ing_00.paa", 220, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa", 221, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa", 222, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_ing_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_ing_00.paa", 223, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_dismount_l_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_dismount_l_00.paa", 224, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_dismount_r_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_dismount_r_00.paa", 225, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_idle_01.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_idle_01.paa", 226, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_mount_l_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_mount_l_00.paa", 227, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_mount_r_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_mount_r_00.paa", 228, false },
        { "character/motion/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_takeoff_00.paa", "character/motion/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_idle_01.paa", 229, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", nullptr, 230, true },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_run_f_ing_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 231, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_runfast_f_ing_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 232, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walk_f_ing_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 233, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_75d_ing_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 234, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_75u_ing_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 235, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_ing_00_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 236, false },
        { "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_std_idle_01_lod.paa", "character/motion/motion_lod__/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 237, false },
        { "character/motion/motion_lod__/1_pc/1_phm/cd_phm_rd_orca_basic_00_00_nor_move_underwater_walkfast_f_ing_00_lod.paa", nullptr, 238, false },
        { "character/motion/motion_lod__/1_pc/1_phm/cd_phm_rd_orca_basic_00_00_nor_std_underwater_idle_00_lod.paa", nullptr, 239, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_run_f_ing_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_run_f_ing_00_lod.paa", 240, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_runfast_f_ing_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_runfast_f_ing_00_lod.paa", 241, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walk_f_ing_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walk_f_ing_00_lod.paa", 242, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_75d_ing_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_75d_ing_00_lod.paa", 243, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_75u_ing_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_75u_ing_00_lod.paa", 244, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_ing_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_ing_00_lod.paa", 245, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_dismount_l_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_dismount_l_00_lod.paa", 246, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_dismount_r_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_dismount_r_00_lod.paa", 247, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_idle_01_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 248, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_mount_l_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_mount_l_00_lod.paa", 249, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_mount_r_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_mount_r_00_lod.paa", 250, false },
        { "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_takeoff_00_lod.paa", "character/motion/motion_lod__/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_idle_01_lod.paa", 251, false },
        { "character/prefab/2_mon/cd_m0004_00_dragon/cd_m0004_00_phoenix/cd_m0004_00_phoenix_00_0001.prefabdata_xml", nullptr, 252, false },
        { "character/texture/cd_r0032_00_speeder_0001.dds", "character/texture/cd_t0000_broom_0001.dds", 253, false },
        { "character/texture/cd_r0032_00_speeder_0001_n.dds", "character/texture/cd_t0000_broom_0001_n.dds", 254, false },
        { "character/texture/cd_r0032_00_speeder_0001_sp.dds", "character/texture/cd_t0000_broom_0001_sp.dds", 255, false },
        { "ui/texture/cd_icon_map_speeder.dds", "ui/texture/image/customizeimage/cd_customize_empty_image.dds", 256, false },
        { "ui/texture/image/portraitimage/cd_mercenary_portrait_riding_speeder_1.dds", "ui/texture/image/portraitimage/cd_mercenary_portrait_domestic_animal_riding_alpineibex_1.dds", 257, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_run_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_runfast_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walk_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_move_walkfast_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_speed_basic_00_00_nor_std_idle_01.paa_metabin", "actionchart/bin__/animmeta/1_pc/1_phm/00_riding/cd_phm_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_run_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_run_f_ing_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_runfast_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_runfast_f_ing_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walk_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walk_f_ing_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_75d_ing_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_75u_ing_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_move_walkfast_f_ing_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_move_walkfast_f_ing_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_dismount_l_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_dismount_l_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_dismount_r_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_dismount_r_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_idle_01.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_mount_l_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_mount_l_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_mount_r_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_mount_r_00.paa_metabin", 0, false },
        { "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_speed_basic_00_00_nor_std_takeoff_00.paa_metabin", "actionchart/bin__/animmeta/4_riding/cd_r0032_00_broom/cd_rd_broom_basic_00_00_nor_std_idle_01.paa_metabin", 0, false },
        { "actionchart/bin__/attackinfo/upperaction/2_mon/m0010_tanksmall_upper.paatt", "actionchart/bin__/attackinfo/upperaction/2_mon/m0004_ride_dragon_upper.paatt", 0, false },
        { "actionchart/bin__/attackinfo/upperaction/4_riding/r0014_boat_upper.paatt", "actionchart/bin__/attackinfo/upperaction/2_mon/m0004_dragon_upper.paatt", 0, false },
        { "character/bin__/meshphysics/4_riding/cd_r0032_00_broom/cd_r0032_00_speed_0001.hkx", "character/bin__/meshphysics/4_riding/cd_r0032_00_broom/cd_r0032_00_broom_0001.hkx", 0, false },
    };
}
