#pragma once
#include <cstdint>

#include "game/hoverpatches.h"

// Generated by private/research/newmount/takeoff_patches.py from the
// Wyvern's riding lower chart (build 1.0.0.2976). The takeoff no longer
// counts as airborne, so the RideOn chart's aim IK waits for flight.
namespace bm::broomchart
{
    inline constexpr HoverPatch kTakeoffPatches[] = {
        { 1, 0x0B848, 0x00000100, 0x00000000 },   // m0004_ride_dragon_lower takeoff 117F8F51: airborne bit 40 off
    };
}
